# 1. Setting

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import koreanize_matplotlib
import seaborn as sns

# 2. Data check

In [29]:
data_path = 'mosquito_data.csv'
data = pd.read_csv(data_path, encoding='cp949')

In [30]:
df = data.rename(columns={
    '모기지수 발생일': 'mosquito_date',
    '모기지수(수변부)': 'mosquito_value_water',
    '모기지수(주거지)': 'mosquito_value_house',
    '모기지수(공원)': 'mosquito_value_park'
})

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2023 entries, 0 to 2022
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   mosquito_date         2023 non-null   object
 1   mosquito_value_water  2023 non-null   float64
 2   mosquito_value_house  2023 non-null   float64
 3   mosquito_value_park   2023 non-null   float64
dtypes: float64(3), object(1)
memory usage: 63.3+ KB

In [32]:
df['mosquito_date'] = pd.to_datetime(df['mosquito_date'], format='%Y-%m-%d')

In [33]:
df.describe()

,mosquito_date,mosquito_value_water,mosquito_value_house,mosquito_value_park
count,2023,2023.000000,2023.000000,2023.000000
mean,2021-07-27 06:01:36.094908672,218.778596,187.173900,189.838112
min,2016-05-01 00:00:00,0.000000,0.000000,0.000000
25%,2018-09-06 12:00:00,93.350000,35.100000,37.900000
50%,2021-08-03 00:00:00,100.000000,52.400000,58.700000
75%,2024-06-06 12:00:00,274.600000,274.600000,274.600000
max,2026-10-21 00:00:00,1000.000000,1000.000000,1000.000000
std,NaN,235.554534,252.963117,251.482204

In [34]:
df.head()

,mosquito_date,mosquito_value_water,mosquito_value_house,mosquito_value_park
0,2026-10-21,66.5,27.2,25.6
1,2026-10-20,30.5,14.4,13.1
2,2026-10-19,73.0,27.1,29.3
3,2026-10-18,81.9,34.0,37.3
4,2026-10-17,69.4,27.9,29.0